### ISSUE TITLE
formulation source

### ISSUE THREAD

**Issue by masoudMZB** [Sato-Kunihiko/audio-SNR#13]
Hello and thanks for your repository
I want to show some engineers that your implementation is mathematically correct. Your implementation has some differences with this repo https://github.com/sleekEagle/audio_processing/blob/master/mix_noise.py  which causes a different result in SNR 15 for example. Can you help me or refer me to a paper or something like that?

thanks

**Comment by Sato-Kunihiko** [comment]
I checked the repo you mentioned. 
I think the calculation for the desired RMS is different between the repo and mine. The repo calculates like this:
```
RMS_n=math.sqrt(RMS_s**2/(pow(10,SNR/10)))
```
I wonder why the `RMS_s` is squared. And, `SNR/10` should change to `SNR/20` because the equation is supposed to be like the below image.
 ![1534391946541](https://user-images.githubusercontent.com/11371585/150672479-1d4c8456-c284-460e-a6d6-f89f536e4bc1.png)
 
I guess the correct code is like that:
```
RMS_n=math.sqrt(RMS_s/(pow(10,SNR/20)))
```

I don't run the code of the repo, so there may be my misunderstanding. Let me know if you have an additional question.
